name: Deployment

on:
  push:
    branches:
      - main-stable

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: Node.js
      url: https://discord.gg/jpMFy5mPqv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run bot
        shell: bash
        env:
          token: ${{ secrets.TOKEN }}
        run: |
          echo "$token"
          nohup node .
